name:                ATL
version:             0.1.0.0
github:              "Quantumzhao/ATL"
license:             BSD-3-Clause
author:              "Quantumzhao"
maintainer:          "yishanzh@umd.edu"
copyright:           "2023 Quantumzhao"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/TSharp#readme>

dependencies:
- base >= 4.7 && < 5
- mtl >= 0.1
# - utility-ht >= 0.0
- containers >= 0.0
- megaparsec >= 0.0
- extra >= 0.0
- parser-combinators >= 1.3.0

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -Wno-unused-imports
- -Wno-unused-matches
- -Wno-unused-top-binds

library:
  source-dirs: src

executables:
  ATL-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ATL

tests:
  ATL-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ATL
